import { Router } from "express";
import Userroute from "./UserRoutes.js";
import Postroute from "./PostRoutes.js";
import RoleRoute from "./RolesRoutes.js";
import AuthenticationRoutes from "./AuthenticationRoutes.js";
const Route = Router();
Route.use("/Authentication", AuthenticationRoutes);
Route.use("/Role", RoleRoute);
Route.use("/user", Userroute);
Route.use("/post", Postroute);
export default Route;